 : چيست FHS 
 در واقع    به ﻣﺎ توضيح ﻣيده  که فﺎيل FHS هﺎ و دايرکتوری هﺎ چگونه  داخل يک توزيع لينوکس ﻣنﻈﻢ و طبقه بندی ﻣﯽ 
 ﺷوند .سﺎختﺎر فﺎيل بندی هﺎی اصلﯽ لينوکس به صورت يک نمودار درختﯽ ﻣﯽ بﺎﺷد به  اين  صورت که ابتدا يه  root 
 داريﻢ و  در داخل    سﺎختﺎر root فﺎيل اصلﯽ فﺎيل بندی درختﯽ ﻣﺎ  قرار دارد . 
 
 
 
دستورات درون ترﻣينﺎل در جلسه  قبلﯽ  : Ls , pws , man ls, info ls, mkdir, rmdir, touch, cd, rm, stat , mv, cp,  
 
 
توضيحﺎت در  ﻣورد  دستورات : 
Ls:  
اين دستور فﺎيل هﺎ  و دايرکتوری هﺎ  را بدون هيچ اطﻼعﺎتﯽ ﻣﺜل ﺣﺠﻢ و   تﺎريخ و غيره به نمﺎيش ﻣيگذارد  . 
 
Ls -l : 
ﺣﺠﻢ، تﺎريخ و زﻣﺎن آخرين  ويرايش فﺎيل يﺎ دايرکتوری، نﺎم فﺎيل يﺎ فولدر و  ﻣﺎلک  فﺎيل و  سﻄح دسترسﯽ  فﺎيل را نشﺎن  ﻣﯽ دهد . 
 
Ls -a: 
ليست تمام فايل ها شامل فايل های مخفی که با ‘.’ شروع می شوند. 
 
Ls -lht: 
تمام فايل ها را برحسب زمان مرتب ميکند. 
 
Info ls:  
 .lsاطﻼعات جامع در مورد دستور 
 
Pwd: 
اين دستور ادرس مکانی که در انجا هستيم را به ما نشان ميدهد. 
 
Mkdir: 
درست کردن يک داريکتوری با اين دستور. 
 
Rmdir: 
پاک کردن يک دايرکتوری . 
 
Touch: 
ايجاد يک فايل. 
 
Rm: 
پاک کردن فايل همراه با پرسش. 
 
Rm -f: 
  (force)پاک کردن فايل بدون سوال .
 
Rm -r:  
پاک کردن به صورت بازگشتی 
 
Mv: 
انتقال فايل، به کمک اين دستور ميتوان نام فايل ها را نيز تغيير داد. 
 
Cd: 
تغيير مسير دادن در داخل ريشه  
 
Cp -r: 
کپی کردن پوشه به صورت بازگشتی )کل پوشه(  
 
Stat: 
 
نميدونم :( 
 
 
 
 
 
جواب تمرين :    
 
 
 : جز دايرکتوری اصلی لينوکس به شمار ميرود، تمامی اطﻼعات فايل های کاربر در پوشه ای در اين فايل ذخيره می شود. هر Home يوزر در اين دايرکتوری يک فولدر مخصوص به خود را داراست.     cdrom کردن دستگاه های دارای حافظه است. مانند mount ميباشد که مکانی موقت برای mount : مخفف کلمه Mnt ،floppy  ،etc .       ای که در بوت نياز نيستند، در اين پوشه قرار دارد . config کردن بجز فايل های boot : تمامی فايل های مورد نياز برای Boot     :تمامی فايل هايی که به صورت موقت مورد نياز هستند در اين پوشه قرار ميگيرند. Tmp
 
 😊 : اين دايرکتوری مکان خاص برای دستگاه ها است. در لينکوس همچيز يا فايل است يا دايرکتوری! Dev  ( است و شامل فايل هايی می شود که سيستم در حين فعاليت root : اين دايرکتوری يکی از زيرمجموعه های اصلی دايرکتوری اصلی ) Var  (writes data during its operationروی آن ها مينويسد   )    ( از قبيل برنامه ها را درون خود نگه ميداردexecutable : اين دايرکتوری تمامی فايل های قابل اجرا ) Bin  
 : يکی از پر اهميت ترين ساب دايرکتوری ها اين زير مجوعه است، که شامل تمامی فايل های کتابخانه ای، اسناد قابل اجرا، فونت ها و Usr ... کاربر ميباشد. 
